# Generated by Django 3.2.9 on 2021-11-15 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ENGINE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True, verbose_name='Название')),
                ('text', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('unique_code', models.CharField(max_length=150, unique=True, verbose_name='Идентификатор')),
                ('parsed', models.IntegerField(blank=True, null=True, verbose_name='Спаршено объявлений')),
                ('status', models.BooleanField(blank=True, default=False, verbose_name='Статус')),
                ('message', models.TextField(blank=True, null=True, verbose_name='Сообщение')),
                ('error', models.TextField(blank=True, null=True, verbose_name='Код ошибки')),
                ('current_log', models.TextField(blank=True, null=True, verbose_name='Актуальный лог')),
                ('full_log', models.TextField(blank=True, null=True, verbose_name='Полный лог')),
                ('timer', models.IntegerField(blank=True, default=5, null=True, verbose_name='Задержка прослушки (сек)')),
            ],
            options={
                'verbose_name': 'Движок',
                'verbose_name_plural': 'Движки',
            },
        ),
        migrations.CreateModel(
            name='Parser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, unique=True, verbose_name='Название')),
                ('text', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('source', models.CharField(blank=True, max_length=150, null=True, verbose_name='Источник')),
                ('unique_code', models.CharField(max_length=150, unique=True, verbose_name='Идентификатор')),
                ('status', models.BooleanField(blank=True, default=False, verbose_name='Статус')),
                ('time_started', models.DateTimeField(blank=True, null=True, verbose_name='Время последнего запуска')),
                ('time_finished', models.DateTimeField(blank=True, null=True, verbose_name='Время остановки')),
                ('offers_parsed', models.IntegerField(blank=True, default=None, null=True, verbose_name='Спаршено объявлений')),
                ('message', models.TextField(blank=True, null=True, verbose_name='Сообщение')),
                ('error', models.TextField(blank=True, null=True, verbose_name='Все ошибки')),
                ('current_error', models.TextField(blank=True, null=True, verbose_name='Актуальные ошибки')),
                ('timer', models.IntegerField(blank=True, default=3600, null=True, verbose_name='Задержка между прогонами (сек)')),
                ('parsed', models.IntegerField(default=0, verbose_name='Спаршено объявлений')),
            ],
            options={
                'verbose_name': 'Парсер',
                'verbose_name_plural': 'Парсеры',
            },
        ),
    ]
