# Generated by Django 3.2.9 on 2022-04-14 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ENGINE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True, verbose_name='Название')),
                ('text', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('unique_code', models.CharField(max_length=150, unique=True, verbose_name='Идентификатор')),
                ('parsed', models.IntegerField(blank=True, null=True, verbose_name='Спаршено объявлений')),
                ('status', models.BooleanField(blank=True, default=False, verbose_name='Статус')),
                ('message', models.TextField(blank=True, null=True, verbose_name='Сообщение')),
                ('error', models.TextField(blank=True, null=True, verbose_name='Код ошибки')),
                ('current_log', models.TextField(blank=True, null=True, verbose_name='Актуальный лог')),
                ('full_log', models.TextField(blank=True, null=True, verbose_name='Полный лог')),
                ('timer', models.IntegerField(blank=True, default=5, null=True, verbose_name='Задержка прослушки (сек)')),
            ],
            options={
                'verbose_name': 'Движок',
                'verbose_name_plural': 'Движки',
            },
        ),
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Парсер')),
                ('start_page', models.IntegerField(blank=True, default=1, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Parser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, unique=True, verbose_name='Название')),
                ('text', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('source', models.CharField(blank=True, max_length=150, null=True, verbose_name='Источник')),
                ('unique_code', models.CharField(max_length=150, unique=True, verbose_name='Идентификатор')),
                ('status', models.BooleanField(blank=True, default=False, verbose_name='Статус')),
                ('time_started', models.DateTimeField(blank=True, null=True, verbose_name='Время последнего запуска')),
                ('time_finished', models.DateTimeField(blank=True, null=True, verbose_name='Время остановки')),
                ('offers_parsed', models.IntegerField(blank=True, default=None, null=True, verbose_name='Спаршено объявлений')),
                ('message', models.TextField(blank=True, null=True, verbose_name='Сообщение')),
                ('error', models.TextField(blank=True, null=True, verbose_name='Все ошибки')),
                ('current_error', models.TextField(blank=True, null=True, verbose_name='Актуальные ошибки')),
                ('timer', models.IntegerField(blank=True, default=3600, null=True, verbose_name='Задержка между прогонами (сек)')),
                ('parsed', models.IntegerField(default=0, verbose_name='Спаршено объявлений')),
            ],
            options={
                'verbose_name': 'Парсер',
                'verbose_name_plural': 'Парсеры',
            },
        ),
        migrations.CreateModel(
            name='Proxy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=255, verbose_name='Логин')),
                ('password', models.CharField(max_length=255, verbose_name='Пароль')),
                ('port', models.IntegerField(verbose_name='Порт')),
                ('ip', models.CharField(max_length=255, null=True, unique=True, verbose_name='IP адрес')),
            ],
            options={
                'verbose_name': 'Прокси',
                'verbose_name_plural': 'Прокси',
            },
        ),
        migrations.CreateModel(
            name='ProxyAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=255, verbose_name='Логин')),
                ('password', models.CharField(max_length=255, verbose_name='Пароль')),
                ('active', models.BooleanField(default=False, verbose_name='Действующий')),
            ],
            options={
                'verbose_name': 'Аккаунт прокси',
                'verbose_name_plural': 'Аккаунты прокси',
            },
        ),
        migrations.CreateModel(
            name='VkGroupDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=599, unique=True, verbose_name='Ссылка группу')),
                ('vk_id', models.IntegerField(unique=True, verbose_name='ID ГРУППЫ ВК')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Название группы')),
            ],
            options={
                'verbose_name': 'Группа ВК',
                'verbose_name_plural': 'Группы ВК',
            },
        ),
    ]
