# Generated by Django 3.2.9 on 2022-04-14 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parsers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProxyUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=255, verbose_name='Логин')),
                ('password', models.CharField(max_length=255, verbose_name='Пароль')),
                ('active', models.BooleanField(default=False, verbose_name='Действующий')),
            ],
            options={
                'verbose_name': 'Аккаунт прокси',
                'verbose_name_plural': 'Аккаунты прокси',
            },
        )
    ]
