# Generated by Django 3.2.9 on 2022-03-31 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parsers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Парсер')),
                ('last_page', models.IntegerField(blank=True, default=1, null=True)),
            ],
        ),
    ]
