# Generated by Django 3.2.9 on 2022-04-14 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parsers', '0002_auto_20220414_1440'),
    ]

    operations = [
        migrations.AddField(
            model_name='proxyuser',
            name='port',
            field=models.IntegerField(default=4444, verbose_name='Порт'),
            preserve_default=False,
        ),
    ]
