# Generated by Django 3.2.9 on 2022-04-07 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parsers', '0003_rename_last_page_info_start_page'),
    ]

    operations = [
        migrations.CreateModel(
            name='VkGroupInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=599, unique=True, verbose_name='Ссылка группу')),
                ('vk_id', models.IntegerField(unique=True, verbose_name='id группы ВК. С минусом. "-11111111"')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Название группы')),
            ],
            options={
                'verbose_name': 'Группа ВК',
                'verbose_name_plural': 'Группы ВК',
            },
        ),
    ]
