# Generated by Django 3.2.9 on 2022-04-15 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parsers', '0003_auto_20220414_1519'),
    ]

    operations = [
        migrations.CreateModel(
            name='VkAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Имя')),
                ('token', models.CharField(max_length=400, unique=True, verbose_name='Токен')),
            ],
            options={
                'verbose_name': 'Аккаунт ВК',
                'verbose_name_plural': 'Аккаунты ВК',
            },
        ),
    ]
