# Generated by Django 3.2.9 on 2022-04-07 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parsers', '0003_rename_last_page_info_start_page'),
    ]

    operations = [
        migrations.CreateModel(
            name='VkGroupInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=599, verbose_name='Ссылка группу')),
                ('home_name', models.CharField(db_index=True, max_length=200, verbose_name='Кодовое имя парсера группы')),
                ('vk_id', models.IntegerField()),
            ],
        ),
    ]
