# Generated by Django 3.2.9 on 2022-04-19 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parsers', '0004_auto_20220415_1214'),
    ]

    operations = [
        migrations.AddField(
            model_name='vkaccount',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Действующий'),
        ),
    ]
