# Generated by Django 3.2.9 on 2022-04-19 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parsers', '0004_auto_20220415_1214'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProxyAccount',
        ),
    ]
