# Generated by Django 3.2.9 on 2022-04-07 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parsers', '0004_vkgroupinfo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vkgroupinfo',
            options={'verbose_name': 'Группа ВК', 'verbose_name_plural': 'Группы ВК'},
        ),
        migrations.RemoveField(
            model_name='vkgroupinfo',
            name='home_name',
        ),
        migrations.AlterField(
            model_name='vkgroupinfo',
            name='vk_id',
            field=models.IntegerField(verbose_name='id группы ВК. С минусом. "-11111111"'),
        ),
    ]
