# Generated by Django 3.2.9 on 2022-04-08 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parsers', '0004_vkgroupdetail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vkgroupdetail',
            name='vk_id',
            field=models.IntegerField(unique=True, verbose_name='ID ГРУППЫ ВК'),
        ),
    ]
