# Generated by Django 3.2.9 on 2022-04-07 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parsers', '0004_vkgroupinfo'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='VkGroupInfo',
            new_name='VkGroupDetail',
        ),
    ]
