# Generated by Django 3.2.9 on 2022-04-20 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parsers', '0005_auto_20220419_1631'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramGroupDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=599, unique=True, verbose_name='Ссылка группу')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Название группы')),
            ],
            options={
                'verbose_name': 'Группа Telegram',
                'verbose_name_plural': 'Группы Telegram',
            },
        ),
    ]
