# Generated by Django 3.2.9 on 2022-04-13 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parsers', '0005_alter_vkgroupdetail_vk_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proxy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=255, verbose_name='Логин')),
                ('password', models.CharField(max_length=255, verbose_name='Пароль')),
                ('port', models.IntegerField(verbose_name='Порт')),
                ('ip', models.CharField(max_length=255, null=True, unique=True, verbose_name='IP адрес')),
            ],
            options={
                'verbose_name': 'Прокси',
                'verbose_name_plural': 'Прокси',
            },
        ),
    ]
