# Generated by Django 3.2.9 on 2022-04-22 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parsers', '0006_auto_20220420_1517'),
    ]

    operations = [
        migrations.AddField(
            model_name='vkaccount',
            name='status',
            field=models.BooleanField(blank=True, default=True, verbose_name='Состояние'),
        ),
    ]
