# Generated by Django 3.2.9 on 2022-05-13 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parsers', '0007_auto_20220422_1441'),
    ]

    operations = [
        migrations.AddField(
            model_name='proxy',
            name='status',
            field=models.BooleanField(blank=True, default=True, verbose_name='Состояние'),
        ),
    ]
