# Generated by Django 3.2.9 on 2022-05-22 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parsers', '0008_auto_20220513_1111'),
    ]

    operations = [
    ]
