# Generated by Django 3.2.9 on 2021-11-16 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_auto_20211116_0442'),
    ]

    operations = [
        migrations.AddField(
            model_name='synrateuser',
            name='subscribed',
            field=models.BooleanField(default=False),
        ),
    ]
