# Generated by Django 3.2.9 on 2022-04-20 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0004_tguser_vkuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TgUser',
        ),
        migrations.DeleteModel(
            name='VkUser',
        ),
    ]
