# Generated by Django 3.2.9 on 2021-11-15 22:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        # ('cms', '0023_auto_20211013_1216'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='synrate_main_faq', serialize=False, to='cms.cmsplugin')),
                ('title', models.CharField(default=None, max_length=1000, verbose_name='FAQ title')),
                ('text', models.TextField(verbose_name='FAQ text')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=None, max_length=300, null=True, unique=True, verbose_name='Название')),
                ('home_name', models.CharField(blank=True, default=None, max_length=200, null=True, verbose_name='Источник')),
                ('url', models.CharField(blank=True, default=None, max_length=250, null=True, unique=True, verbose_name='Ссылка на источник')),
                ('location', models.CharField(blank=True, default='РФ', max_length=250, null=True, verbose_name='Регион')),
                ('offer_type', models.CharField(blank=True, default='Продажа', max_length=100, null=True, verbose_name='Тип объявления')),
                ('offer_start_date', models.DateField(blank=True, null=True, verbose_name='Дата начала торгов')),
                ('offer_end_date', models.DateField(blank=True, null=True, verbose_name='Дата завершения торгов')),
                ('owner', models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='Владелец')),
                ('ownercontact', models.CharField(blank=True, default='Не указан', max_length=250, null=True, verbose_name='Контакт владельцы')),
                ('offer_price', models.IntegerField(blank=True, default=None, null=True, verbose_name='Цена')),
                ('additional_data', models.TextField(blank=True, default=None, null=True, verbose_name='Дополнительные данные')),
                ('organisation', models.CharField(blank=True, default=None, max_length=250, null=True, verbose_name='Организация')),
            ],
            options={
                'verbose_name': 'Объявление',
                'verbose_name_plural': 'Объявления',
            },
        ),
    ]
