# Generated by Django 3.2.9 on 2021-11-25 22:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        # ('cms', '0023_auto_20211013_1216'),
        ('synrate_main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='INTRO',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='synrate_main_intro', serialize=False, to='cms.cmsplugin')),
                ('header_text', models.TextField(verbose_name='Текст заголовка')),
                ('first_title', models.CharField(default=None, max_length=1000, verbose_name='Первый заголовок')),
                ('first_text', models.CharField(default=None, max_length=1000, verbose_name='Первый заголовок')),
                ('second_title', models.CharField(default=None, max_length=1000, verbose_name='Первый заголовок')),
                ('second_text', models.CharField(default=None, max_length=1000, verbose_name='Первый заголовок')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
    ]
