# Generated by Django 3.2.9 on 2021-11-25 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('synrate_main', '0002_intro'),
    ]

    operations = [
        migrations.AddField(
            model_name='intro',
            name='goto_text',
            field=models.CharField(default=None, max_length=1000, verbose_name='Текст ссылки на поиск'),
        ),
        migrations.AlterField(
            model_name='intro',
            name='first_text',
            field=models.CharField(default=None, max_length=1000, verbose_name='Первый текст'),
        ),
        migrations.AlterField(
            model_name='intro',
            name='second_text',
            field=models.CharField(default=None, max_length=1000, verbose_name='Второй текст'),
        ),
        migrations.AlterField(
            model_name='intro',
            name='second_title',
            field=models.CharField(default=None, max_length=1000, verbose_name='Второй заголовок'),
        ),
    ]
