# Generated by Django 3.2.9 on 2021-11-28 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('synrate_main', '0004_offer_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='category',
            field=models.CharField(blank=True, default=None, max_length=500, null=True, verbose_name='Категория'),
        ),
        migrations.AddField(
            model_name='offer',
            name='subcategory',
            field=models.CharField(blank=True, default=None, max_length=500, null=True, verbose_name='Подкатегория'),
        ),
    ]
