# Generated by Django 3.2.9 on 2021-11-28 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('synrate_main', '0006_auto_20211128_1432'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='category',
        ),
    ]
