# Generated by Django 3.2.9 on 2021-11-28 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('synrate_main', '0007_remove_offer_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='category',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='synrate_main.offersubcategory', verbose_name='Подкатегория'),
        ),
    ]
