# Generated by Django 3.2.9 on 2021-11-28 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('synrate_main', '0008_offer_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='offersubcategory',
            options={'verbose_name': 'Подкатегория', 'verbose_name_plural': 'Подкатегории'},
        ),
    ]
