# Generated by Django 3.2.9 on 2021-11-30 00:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('synrate_main', '0009_alter_offersubcategory_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='category',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategory', to='synrate_main.offersubcategory', verbose_name='Подкатегория'),
        ),
        migrations.AlterField(
            model_name='offersubcategory',
            name='category',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category', to='synrate_main.offercategory', verbose_name='Категория'),
        ),
    ]
