# Generated by Django 3.2.9 on 2021-12-05 03:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        # ('cms', '0023_auto_20211013_1216'),
        ('synrate_main', '0010_auto_20211130_0003'),
    ]

    operations = [
        migrations.CreateModel(
            name='ABOUT',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='synrate_main_about', serialize=False, to='cms.cmsplugin')),
                ('title', models.TextField(verbose_name='Заголовок')),
                ('text', models.TextField(verbose_name='Текст')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='CONTACT',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='synrate_main_contact', serialize=False, to='cms.cmsplugin')),
                ('name', models.TextField(verbose_name='Имя автора')),
                ('img', models.ImageField(null=True, upload_to='', verbose_name='Фото автора')),
                ('text', models.TextField(null=True, verbose_name='Описание контакта')),
                ('contact_vk', models.CharField(max_length=2000, null=True, verbose_name='Контакт автора (ссылка вк)')),
                ('contact_tg', models.CharField(max_length=2000, null=True, verbose_name='Контакт автора (ссылка тг)')),
                ('contact_phone', models.CharField(max_length=2000, null=True, verbose_name='Контакт автора (номер телефона)')),
                ('contact_email', models.CharField(max_length=2000, null=True, verbose_name='Контакт автора (почта)')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='TITLE',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='synrate_main_title', serialize=False, to='cms.cmsplugin')),
                ('name', models.TextField(verbose_name='Заголовок')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
    ]
