# Generated by Django 3.2.9 on 2021-12-05 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('synrate_main', '0011_about_contact_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='contact_email',
            field=models.CharField(blank=True, max_length=2000, null=True, verbose_name='Контакт автора (почта)'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=2000, null=True, verbose_name='Контакт автора (номер телефона)'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='contact_tg',
            field=models.CharField(blank=True, max_length=2000, null=True, verbose_name='Контакт автора (ссылка тг)'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='contact_vk',
            field=models.CharField(blank=True, max_length=2000, null=True, verbose_name='Контакт автора (ссылка вк)'),
        ),
    ]
