# Generated by Django 3.2.9 on 2022-03-22 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('synrate_main', '0015_alter_offer_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='name',
            field=models.CharField(blank=True, default=None, max_length=300, null=True, verbose_name='Название'),
        ),
    ]
