# Generated by Django 3.2.9 on 2022-03-30 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('synrate_main', '0017_alter_offer_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='url',
            field=models.CharField(blank=True, default=None, max_length=599, null=True, unique=True, verbose_name='Ссылка на источник'),
        ),
    ]
