# Generated by Django 3.2.9 on 2022-04-06 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('synrate_main', '0022_offer_from_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='short_cat',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
