# Generated by Django 3.2.9 on 2022-04-19 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('synrate_main', '0024_offer_owner_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='offer_price',
            field=models.FloatField(blank=True, default=None, null=True, verbose_name='Цена'),
        ),
    ]
