# Generated by Django 3.2.9 on 2022-04-20 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('synrate_main', '0026_tguser_vkuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tguser',
            name='a_data',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='vkuser',
            name='a_data',
            field=models.TextField(null=True),
        ),
    ]
