# Generated by Django 3.2.9 on 2022-05-12 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('synrate_main', '0028_auto_20220512_1054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='slug',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, unique=True, verbose_name='ЧПУ'),
        ),
    ]
