# Generated by Django 3.2.9 on 2022-05-16 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('synrate_main', '0029_alter_offer_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
