# Generated by Django 3.2.9 on 2022-05-18 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('synrate_main', '0030_offer_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='OffersCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('all_count', models.PositiveIntegerField(default=0)),
                ('month_count', models.PositiveIntegerField(default=0)),
                ('today_count', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
