# Generated by Django 3.2.9 on 2022-05-18 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('synrate_main', '0031_offerscount'),
    ]

    operations = [
        migrations.AddField(
            model_name='offerscount',
            name='home_lilter',
            field=models.CharField(choices=[('all', 'source_name'), ('b2b-center', 'source_name'), ('etp-activ', 'source_name'), ('etpgpb', 'source_name'), ('fabrikant', 'source_name'), ('isource', 'source_name'), ('nelikvidi', 'source_name'), ('onlinecontract', 'source_name'), ('roseltorg', 'source_name'), ('tektorg', 'source_name'), ('tenderpro', 'source_name'), ('vk.com', 'source_name')], default='all', max_length=50, verbose_name='Фильтр по источнику предложений'),
        ),
    ]
