# Generated by Django 3.2.9 on 2022-05-22 15:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('synrate_main', '0033_rename_offerscount_offerscounter'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='home',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='synrate_main.parserdetail'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='additional_data',
            field=models.TextField(blank=True, db_index=True, default=None, null=True, verbose_name='Дополнительные данные'),
        ),
        migrations.AlterField(
            model_name='offerscounter',
            name='home_lilter',
            field=models.CharField(choices=[('all', 'Все'), ('b2b-center', 'b2b-center.ru'), ('etp-activ', 'etp-activ.ru'), ('etpgpb', 'etpgpb.ru'), ('fabrikant', 'fabrikant.ru'), ('isource', 'reserve.isource.ru'), ('nelikvidi', 'nelikvidi.com'), ('onlinecontract', 'onlinecontract.ru'), ('roseltorg', 'roseltorg.ru'), ('tektorg', 'tektorg.ru'), ('tenderpro', 'tender.pro'), ('vk.com', 'vk.com'), ('telegram', 'telegram'), ('prostanki', 'prostanki.com'), ('metaprom', 'metaprom.ru'), ('promportal', 'promportal.su')], default='all', max_length=50, verbose_name='Фильтр по источнику предложений'),
        ),
    ]
