# Generated by Django 3.2.9 on 2022-05-22 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('synrate_main', '0034_auto_20220522_1513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='additional_data',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='Дополнительные данные'),
        ),
    ]
