# Generated by Django 3.2.9 on 2022-05-23 10:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('synrate_main', '0035_alter_offer_additional_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='home',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='home', to='synrate_main.parserdetail'),
        ),
    ]
