# Generated by Django 3.2.9 on 2022-05-23 11:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('synrate_main', '0036_alter_offer_home'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='home',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home', to='synrate_main.parserdetail'),
        ),
    ]
