# Generated by Django 3.2.9 on 2022-05-24 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('synrate_main', '0037_alter_offer_home'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchQueries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phrase', models.CharField(max_length=255, verbose_name='Фраза')),
                ('slug', models.CharField(max_length=255, verbose_name='ЧПУ')),
            ],
        ),
    ]
