# Generated by Django 3.2.9 on 2022-05-24 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('synrate_main', '0038_searchqueries'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SearchQueries',
            new_name='SearchQuery',
        ),
    ]
