# Generated by Django 3.2.9 on 2022-05-24 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('synrate_main', '0039_rename_searchqueries_searchquery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchquery',
            name='slug',
            field=models.SlugField(max_length=250, unique=True, verbose_name='ЧПУ'),
        ),
    ]
