# Generated by Django 3.2.9 on 2022-05-24 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('synrate_main', '0040_alter_searchquery_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchquery',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
