# Generated by Django 3.2.9 on 2022-05-24 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('synrate_main', '0041_searchquery_is_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='searchquery',
            options={'verbose_name': 'Поисковый запрос', 'verbose_name_plural': 'Поисковые запросы'},
        ),
        migrations.AddField(
            model_name='searchquery',
            name='search_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
