# Generated by Django 3.2.9 on 2022-05-24 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('synrate_main', '0043_auto_20220524_2008'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='is_active',
            field=models.BooleanField(default=0),
        ),
    ]
