# Generated by Django 3.2.9 on 2022-06-13 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('synrate_main', '0045_alter_banner_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='banner',
            options={'verbose_name': 'Баннер', 'verbose_name_plural': 'Баннеры'},
        ),
        migrations.AlterField(
            model_name='banner',
            name='banner_type',
            field=models.CharField(choices=[('right', 'Баннер справа'), ('top', 'Баннер сверху'), ('bottom', 'Баннер снизу')], default='right', max_length=50, verbose_name='тип баннера'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='code',
            field=models.TextField(verbose_name='Код баннера'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='is_active',
            field=models.BooleanField(default=0, verbose_name='Активен'),
        ),
    ]
