# Generated by Django 3.2.9 on 2022-06-13 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('synrate_main', '0046_auto_20220613_2101'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchquery',
            name='offers_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество объявлений для запроса'),
        ),
    ]
